language: swift
osx_image: xcode10.2
env:
  global:
    - PROJECT=Tempura.xcworkspace
  matrix:
    - SCHEME="Tempura"
      SDK=iphonesimulator12.0
      SIMULATOR="platform=iOS Simulator,OS=12.0,name=iPhone 8"

before_install:
  - pod repo update > /dev/null

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - instruments -s devices

  # Build Framework in Debug and Run Tests if specified
  - travis_retry xcodebuild -workspace $PROJECT -scheme "$SCHEME" -sdk $SDK test -destination "$SIMULATOR" | xcpretty -c
